/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Himanshu
 */
public class Converter extends javax.swing.JFrame {

    /**
     * Creates new form Converter
     */
    public Converter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        binary = new javax.swing.JRadioButton();
        octal = new javax.swing.JRadioButton();
        decimal = new javax.swing.JRadioButton();
        hex = new javax.swing.JRadioButton();
        hex1 = new javax.swing.JRadioButton();
        decimal1 = new javax.swing.JRadioButton();
        octal1 = new javax.swing.JRadioButton();
        binary1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("NUMBER SYSTEM CONVERTER");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ENTER THE NUMBER");

        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        binary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        binary.setText("BINARY");
        binary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binaryActionPerformed(evt);
            }
        });

        octal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        octal.setText("OCTAL");
        octal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octalActionPerformed(evt);
            }
        });

        decimal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decimal.setText("DECIMAL");

        hex.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hex.setText("HEX");

        hex1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        hex1.setText("HEX");

        decimal1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        decimal1.setText("DECIMAL");

        octal1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        octal1.setText("OCTAL");

        binary1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        binary1.setText("BINARY");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("RESULT");

        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(binary)
                                        .addComponent(octal)
                                        .addComponent(decimal)
                                        .addComponent(hex))
                                    .addGap(47, 47, 47)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(binary1)
                                        .addComponent(octal1)
                                        .addComponent(decimal1)
                                        .addComponent(hex1)
                                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(108, 108, 108)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton2)
                                        .addComponent(result))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(binary)
                            .addComponent(hex1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(octal)
                            .addComponent(decimal1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decimal)
                            .addComponent(octal1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hex)
                            .addComponent(binary1))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void binaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_binaryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String str1=null,str2=null,str3=null,dec2=null;
int dec1=0;
if(binary.isSelected()==true && decimal1.isSelected()==true)
{
    String bindec=input.getText();
    str1=bindec;
    int dec=Integer.parseInt(bindec,2);
    dec1=dec;
    result.setText(""+dec1);
}
else if((binary.isSelected()==true) && (hex1.isSelected()==true)){
    String binhex=input.getText();
    str2=binhex;
    int d=Integer.parseInt(str2,2);
    String hex=Integer.toHexString(d);
    dec2=hex;
    result.setText(dec2);
    }
else if((binary.isSelected()==true) && (octal1.isSelected()==true))
{
    String binoct=input.getText();
    str3=binoct;
    int d=Integer.parseInt(str3,2);
    String oct=Integer.toOctalString(d);
    result.setText(oct);
}
else if((octal.isSelected()==true) && (hex1.isSelected()==true))
{
    String octhex=input.getText();
    str3=octhex;
    int d=Integer.parseInt(str3,8);
    String oct=Integer.toHexString(d);
    result.setText(oct);
}
else if((octal.isSelected()==true) && (decimal1.isSelected()==true))
{
    String octdec=input.getText();
    str3=octdec;
    int d=Integer.parseInt(str3,8);
    String oct=Integer.toString(d);
    result.setText(oct);
}
else if((octal.isSelected()==true) && (binary1.isSelected()==true))
{
    String octbin=input.getText();
    str3=octbin;
    int d=Integer.parseInt(str3,8);
    String oct=Integer.toBinaryString(d);
    result.setText(oct);
}
else if((decimal.isSelected()==true) && (hex1.isSelected()==true))
{
    String dechex=input.getText();
    str3=dechex;
    int d=Integer.parseInt(str3,10);
    String dec=Integer.toHexString(d);
    result.setText(dec);
}
else if((decimal.isSelected()==true) && (octal1.isSelected()==true))
{
    String decoct=input.getText();
    str3=decoct;
    int d=Integer.parseInt(str3,10);
    String dec=Integer.toOctalString(d);
    result.setText(dec);
}
else if((decimal.isSelected()==true) && (binary1.isSelected()==true))
{
    String decbin=input.getText();
    str3=decbin;
    int d=Integer.parseInt(str3,10);
    String dec=Integer.toBinaryString(d);
    result.setText(dec);
}
else if((hex.isSelected()==true) && (decimal1.isSelected()==true))
{
    String hexdec=input.getText();
    str3=hexdec;
    int d=Integer.parseInt(str3,16);
    String hex=Integer.toString(d);
    result.setText(hex);
}
else if((hex.isSelected()==true) && (octal1.isSelected()==true))
{
    String hexoct=input.getText();
    str3=hexoct;
    int d=Integer.parseInt(str3,16);
    String hex=Integer.toOctalString(d);
    result.setText(hex);
}
else if((hex.isSelected()==true) && (binary1.isSelected()==true))
{
    String hexbin=input.getText();
    str3=hexbin;
    int d=Integer.parseInt(str3,16);
    String hex=Integer.toBinaryString(d);
    result.setText(hex);
}


    }//GEN-LAST:event_jButton1ActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
input.setText("");
result.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void octalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_octalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton binary;
    private javax.swing.JRadioButton binary1;
    private javax.swing.JRadioButton decimal;
    private javax.swing.JRadioButton decimal1;
    private javax.swing.JRadioButton hex;
    private javax.swing.JRadioButton hex1;
    private javax.swing.JTextField input;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton octal;
    private javax.swing.JRadioButton octal1;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
